### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Edge7481** [Ynng/Starter-Hacks-2020#2]
Selective content blocking
Rationale: Some domains contain both academic and distracting information. This should correctly determine the type of information such that it would block useless sites but allow for useful ones (idk why u would use reddit to do research in the first place)

If we want to use "AI" or "Machine Learning" then please do python
Word processing: [NLTK](https://www.nltk.org/) or [SpaCy](https://spacy.io/)
Training: Tensorflow

if it's just NLP and no ML then consider [node-nlp](https://www.npmjs.com/package/node-nlp) and make this an extension or a script.

**Comment by Edge7481** [comment]
Tab for cause
Charity?

Pros: Can do this before dinner
Cons: It's not ours lmao

**Comment by Edge7481** [comment]
DIsease risk score prediction

Read from a database of patients of a particular condition
Identify all attributes of each patient

Mystery step: Create and train a model so that it can identify patients with specific attributes such that they are at risk of a readmission. Give each patient a score of readmission in the next  X hours/days. 

Notify the physician to pay attention to the patient. Use this to save money for companies

**Comment by Edge7481** [comment]
Chrome extension that detects what you are reading
Warns you if there's too many suicidal thoughts?

**Comment by Edge7481** [comment]
Discord plugin that scans chat to determine mental health issues.

Export chat history (realtime preferably)
Identify key characteristics that are linked to a specific attribute
Look for occurrences for these characteristics in each user
Notify users

**Comment by Edge7481** [comment]
[Quoting this](https://github.com/Ynng/Starter-Hacks-2020/issues/2#issuecomment-575933632)

Use NLP in general for discord. Doesn't have to be mental illness

**Comment by Edge7481** [comment]
Doujinshi scanlation
Gets images directly or from an imageboard url
Use OCR to recognize the texts in each image
Send the text to translate API to get a translated version
Typeset the text into the bubbles of the images
Export the images as psd/pdf/jpg

**Comment by Ynng** [comment]
An app in one calculator:
PWA,
+[Numi](https://github.com/nikolaeu/Numi)
+Tydlig
+Spreadsheet

conversion + variables + grraphing? + formula auto complete

**Comment by Edge7481** [comment]
List the known values, list what you want. Get suggestions for useable formulas to derive the answer.
Autocomplete similar to vscode?
